[package]
name = "assembler"
version = "1.0.0"
edition = "2021"
description = "Assembler for the virtual machine"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
indoc = "2.0.3"
lazy_static = "1.4.0"

[dependencies.rust_vm_lib]
path = "../rust_vm_lib"
