[package]
name = "disassembler"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = { version = "3.2.20", features = ["derive"] }
lazy_static = "1.4.0"

[dependencies.rust_vm_lib]
path = "../rust_vm_lib"
